# 1. Create a 3x3x3 array with random values 

In [4]:
import numpy as np
a=np.random.uniform((3,3,3))
print (a)

[1.54611426 2.63431148 2.14149087]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [10]:
a=np.diag(1+np.arange(4), k = -1)
print (a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [13]:
a = np.zeros ((8,8), dtype=int)
a[1::2, ::2]= 1
a[::2, 1::2] = 1
print (a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [19]:
a= np.random.random((5,5))
amax, amin = a.max(), a.min()
a= (a-amin)/(amax-amin)
print (a)

[[0.96449293 0.22804076 0.37634135 0.24634575 0.83114684]
 [0.78384374 1.         0.17601936 0.44584086 0.06697765]
 [0.         0.77314934 0.84208556 0.00255697 0.67393993]
 [0.44308132 0.53273683 0.2237252  0.06308141 0.7477243 ]
 [0.03938144 0.07093763 0.4950748  0.258532   0.45100748]]


# 5.  How to find common values between two arrays?

In [33]:
A= np.random.randint(0,2,5)
B= np.random.randint(0,2,5)
print(np.intersect1d(A, B))

[0 1]


# 6.How to get the dates of yesterday, today and tomorrow?

In [36]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)
today     = np.datetime64('today', 'D')
print(today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2020-07-25
2020-07-26
2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [20]:
A= np.random.randint(0,2,5)
B= np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [21]:
a= np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.56828457 0.67312585 0.38528455 0.13601075 0.62434081 0.27310472
 0.         0.67767736 0.33766246 0.82365623]


# 9. How to print all the values of an array?

In [25]:
np.set_printoptions(threshold=np.sys.maxsize)
a= np.zeros((25,25))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

# 10.Subtract the mean of each row of a matrix

In [30]:
a= np.random.rand(5, 10)
print(a)
b= a - a.mean(axis=1, keepdims=True)
print(b)

[[0.37724958 0.08205943 0.85739216 0.87582055 0.77169347 0.73927363
  0.66843866 0.37981235 0.72029062 0.36485549]
 [0.82450895 0.09014748 0.70615806 0.97458388 0.93787748 0.29592732
  0.83404452 0.67222807 0.96056253 0.5037931 ]
 [0.29911273 0.29126379 0.59949768 0.4371018  0.42774319 0.4720698
  0.01911378 0.24119801 0.22801621 0.5641091 ]
 [0.79038094 0.46298736 0.31281799 0.89373162 0.9337209  0.43750318
  0.44704446 0.56503903 0.00452526 0.8617616 ]
 [0.72537001 0.17034872 0.67094018 0.74239783 0.74680022 0.04150872
  0.88913857 0.33603687 0.95270294 0.62124281]]
[[-0.20643901 -0.50162916  0.27370357  0.29213196  0.18800487  0.15558504
   0.08475007 -0.20387625  0.13660203 -0.2188331 ]
 [ 0.14452581 -0.58983566  0.02617492  0.29460074  0.25789435 -0.38405582
   0.15406138 -0.00775507  0.28057939 -0.17619004]
 [-0.05880988 -0.06665882  0.24157507  0.07917919  0.06982058  0.11414719
  -0.33880883 -0.1167246  -0.1299064   0.20618649]
 [ 0.21942971 -0.10796388 -0.25813324  0.32278038 

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [31]:
a= np.ones(10)
b= np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)


[3. 3. 4. 3. 1. 3. 4. 1. 5. 3.]


# 12.How to get the diagonal of a dot product?

In [32]:
a= np.random.randint(0,10,(3,3))
b= np.random.randint(0,10,(3,3))
np.diag(np.dot(a, b))

array([60, 18, 30])

# 13.How to find the most frequent value in an array?

In [38]:
a= np.random.randint(0, 10, 20)
print(a)
print(np.bincount(a).argmax())

[1 3 6 7 5 9 7 3 8 1 9 4 2 1 6 3 6 9 5 8]
1


14.How to get the n largest values of an array

In [39]:
a= np.arange(20)
print(a)
np.random.shuffle(a)
n = 1
print (a[np.argsort(a)[-n:]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19]


# 15.How to create a record array from a regular array?

In [40]:
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print(arra1)
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
